services:
  postgres:
    image: postgres:17
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  redis:
    image: redis:7
    container_name: redis_container
    restart: always
    ports:
      - "6739:6739"
    
  mailpit:
    image: axllent/mailpit
    container_name: mailpit_container
    restart: always
    ports:
     - "1025:1025"
     - "8025:8025"
    
  web:
    build: .
    container_name: "django_container"
    command: "python manage.py runserver 0.0.0.0:8003"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8003:8003"
    depends_on:
      - postgres
      - redis

  celery:
    build: .
    container_name: "celery_container"
    command : "celery -A config  beat -l info"
    volumes: 
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: