# Generated by Django 6.0.5 on 2026-05-29 12:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_career'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='career',
            unique_together={('user', 'club', 'start')},
        ),
    ]
